#!/usr/bin/env python
# Build the unit tests

def build (bld):
    bld.program (
        source = bld.path.ant_glob ("juce/**/*.cpp"),
        includes = [ 'juce' ],
        target = '../bin/test_juce',
        use = [ 'LUA', 'ELEMENT', 'ELEMENT_JUCE', 'UI_objects' ],
        install_path = None
    )

    bld.program (
        source = bld.path.ant_glob ("*.cpp") + \
                bld.path.ant_glob ("scripting/*.cpp"),
        includes = [ '.' ],
        target = '../bin/test_element',
        use = [ 'LUA', 'ELEMENT', 'ELEMENT_JUCE', 'UI_objects', 'BOOST_TEST' ],
        install_path = None
    )
