import plugins

def build (bld):
    opengl = bld (
        features = 'cxx cxxshlib',
        source = '''
            buffer.cpp
            opengl.cpp
            program.cpp
            shader.cpp
            stencil.cpp
            texture.cpp
            texture2d.cpp
        '''.split(),
        includes = [ '.', '../../libs/element/include', 'glad/include' ],
        name            = 'OPENGL_ELEMENT',
        target          = 'opengl',
        cppflags        = [],
        linkflags       = [],
        env             = plugins.derive_env (bld),
        install_path    = plugins.install_path (bld, 'opengl'),
        use             = []
    )

    if bld.host_is_linux():
        opengl.source.append ('x11_glx.cpp')
        opengl.use.append ('X11')
        opengl.env.append_unique ('LIB_XCB', [ 'X11-xcb' ])
        opengl.use.append ('XCB')
    elif bld.host_is_windows():
        opengl.source.append ('win32_wgl.cpp')
    elif bld.host_is_mac():
        opengl.source.append ('mac.mm')

    bld (
        features        = 'subst',
        source          = 'manifest.lua',
        target          = 'manifest.lua',
        install_path    = plugins.install_path (bld, 'opengl')
    )
