#!/bin/env python
import plugins

def build (bld):
    jack = bld (
        features        = 'c cshlib',
        includes        = [ '../../libs/element/include' ],
        source          = [ 'jack.c' ],
        name            = 'jack',
        target          = 'jack',
        cflags          = [ '-fvisibility=hidden' ],
        env             = plugins.derive_env (bld),
        install_path    = plugins.install_path (bld, 'jack')
    )

    bld (
        features        = 'subst',
        source          = 'manifest.lua',
        target          = 'manifest.lua',
        install_path    = plugins.install_path (bld, 'jack')
    )
