#!/usr/bin/python

def build (bld):
    console = bld.program (
        source      = [ 'interpreter.cpp', 'main.cpp' ],
        includes    = [ '.' ],
        target      = '../bin/element',
        name        = 'ElementApp',
        env         = bld.env.derive(),
        use         = [ 'DEPENDS', 'ELEMENT' ],
        linkflags   = [],
        defines     = []
    )

    if isinstance(bld.env.LIB_READLINE, list) and len(bld.env.LIB_READLINE) > 0:
        console.use.append ('READLINE')
        console.defines.append ('LUA_USE_READLINE=1')
